language: scala
sudo: false
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6
jdk:
  - oraclejdk8
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
cache:
  directories:
    - $HOME/.ivy2/cache
matrix:
  include:
  - scala: 2.13.0-M4
    script:
    - sbt "++ ${TRAVIS_SCALA_VERSION}!"
      scalate-jsp-converter/compile
      scalate-war/compile
      scalate-camel/compile
      scalate-jruby/compile
      scalate-pegdown/compile
      scalate-markdownj/compile
      scalate-guice/compile
      scalate-jrebel/compile
