language: scala
sudo: false
scala:
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4
jdk:
  - oraclejdk8
matrix:
  include:
  - jdk: oraclejdk10
    scala: 2.12.6
  - scala: 2.13.0-M5
    script:
    - sbt "++ ${TRAVIS_SCALA_VERSION}!" compile
install:
  - sudo apt-get --yes install python-pygments
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
cache:
  directories:
    - $HOME/.ivy2/cache
